### ISSUE TITLE
Remove engines.node max version limit

### ISSUE THREAD

**Issue by uncenter** [zeroby0/netlify-plugin-11ty#3]
The README FAQs list that Netlify doesn't support some node versions. This may be historically true but AFAIK that has changed.

Via [the Netlify docs](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript):
> Both methods above will accept any released version of Node.js, or any valid string that [nvm](https://github.com/nvm-sh/nvm#nvmrc) understands.

**TLDR; Netlify supports "any released version of Node.js".** I can confirm this as I successfully deploy my Netlify site using Node.js 20.

**Comment by zeroby0** [comment]
Thank you so much!

I have removed the max version limit and published a new release on npm :D
